/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.8 */
/* Sun Jan 29 09:14:16 2017 */

/* parameterized module instance */
a2f_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .RCNT( ), .Empty( ), .Full( ));
