onerror { resume }
transcript off
add wave -noreg -logic {/top_vlg_tst/i1/sdr_inst/en}
add wave -noreg -logic {/top_vlg_tst/i1/sdr_inst/ft_clk}
add wave -noreg -vgroup "TB"  {/top_vlg_tst/ft_data} {/top_vlg_tst/treg_ft_data}
add wave -noreg -vgroup "FT"  {/top_vlg_tst/ft_be} {/top_vlg_tst/ft_data} {/top_vlg_tst/ft_oe_n} {/top_vlg_tst/ft_rxf_n} {/top_vlg_tst/ft_rd_n} {/top_vlg_tst/ft_txe_n} {/top_vlg_tst/ft_wr_n} {/top_vlg_tst/i1/sdr_inst/fsm_inst/wr_local} {/top_vlg_tst/i1/sdr_inst/fsm_inst/have_rd_chance} {/top_vlg_tst/i1/sdr_inst/fsm_inst/rd_enough} {/top_vlg_tst/i1/sdr_inst/fsm_inst/have_unread_word_a2f} {/top_vlg_tst/i1/sdr_inst/fsm_inst/have_wr_chance} {/top_vlg_tst/i1/sdr_inst/fsm_inst/no_more_read} {/top_vlg_tst/i1/sdr_inst/fsm_inst/no_more_write}
add wave -noreg -vgroup "SEL_F2A"  {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/clk_i} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/data_i} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/we_i} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/fifo_data_o} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/fifo_we_o} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/cpu_data_o} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/cpu_we_o} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/mode} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/packet_cnt} {/top_vlg_tst/i1/sdr_inst/sel_f2a_inst/req_packets}
add wave -noreg -vgroup "F2A_FIFO"  {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/WrClock} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/WrEn} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/Data} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/RdClock} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/RdEn} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/Q} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/Empty} {/top_vlg_tst/i1/sdr_inst/f2a_fifo_inst/Full}
add wave -noreg -vgroup "SEL_A2F"  {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/state} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/packet_cnt} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/available_o} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/clk_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/data_o} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/re_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/header} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/fifo_enough_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/fifo_data_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/fifo_re_o} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/cpu_data_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/cpu_fifo_blks_done} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/fifoout_blkcnt_i} {/top_vlg_tst/i1/sdr_inst/sel_a2f_inst/cpu_re_o}
add wave -noreg -vgroup "A2F_FIFO"  {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/Data} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/WrClock} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/RdClock} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/WrEn} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/RdEn} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/Q} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/Empty} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/Full} {/top_vlg_tst/i1/sdr_inst/a2f_fifo_inst/AlmostFull}
add wave -noreg -vgroup "AFE:TX"  {/top_vlg_tst/i1/sdr_inst/afe_inst/reset_n} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_sclk_2x} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_fifo_empty} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_fifo_req} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_fifo_clk} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_fifo_data} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_clk_2x} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_d} {/top_vlg_tst/i1/sdr_inst/afe_inst/tx_sel}
add wave -noreg -vgroup "AFE:RX"  {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_clk_2x} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_fifo_clk} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_fifo_full} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_fifo_wr} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_fifo_data} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_sclk_2x} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_sel} {/top_vlg_tst/i1/sdr_inst/afe_inst/rx_d}
cursor "Cursor 1" 306340133.92ps  
transcript on
