/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.8 */
/* Sun Jan 29 09:13:24 2017 */

/* parameterized module instance */
f2a_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .Empty( ), .Full( ));
